# Introduction

1/ Python If-Else

In [ ]:
if __name__ == '__main__':
    n = int(input().strip())
    if n % 2 == 1:
        print('Weird')
    else:
        if 2 <= n <= 5:
            print('Not Weird')
        elif 6 <= n <= 20:
            print('Weird')
        else:
            print('Not Weird')

24
Not Weird


2/ Arithmetic Operators

The provided code stub reads two integers from STDIN, a and b. Add code to print three lines where:

The first line contains the sum of the two numbers.

The second line contains the difference of the two numbers (first - second).

The third line contains the product of the two numbers.

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b, a-b, a*b, sep='\n')

3
5
8
-2
15


3/ Python: Division

The provided code stub reads two integers, a and b, from STDIN.

Add logic to print two lines. The first line should contain the result of integer division, a // b. The second line should contain the result of float division, a / b.

No rounding or formatting is necessary.

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a // b, '%.11f' % (a / b), sep='\n')

4
3
1
1.33333333333


4/ Loops

The provided code stub reads and integer, n, from STDIN. For all non-negative integers i < n, print i^2.

In [ ]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)

9
0
1
4
9
16
25
36
49
64


4/ Write a function (Leap Year)

(same like last question of Nordic Coder Exercise 3)

Given a year, determine whether it is a leap year. If it is a leap year, return the Boolean True, otherwise return False.

Note that the code stub provided reads from STDIN and passes arguments to the is_leap function. It is only necessary to complete the is_leap function.

In [ ]:
def is_leap(year):
    leap = False
    if year % 400 == 0 or year % 4 == 0 and year % 100 != 0:
        leap = True
    return leap
is_leap(int(input()))
#year = int(input())    

1992


True

5/ Print Function

Print a string of numbers <= given input w/o space.

The included code stub will read an integer, n, from STDIN.

Without using any string methods, try to print the following:

123 ... n

Note that "..." represents the consecutive values in between.

In [ ]:
if __name__ == '__main__':
    n = int(input())
    lst = []
    for i in range(1, n+1):
        lst.append(i)
    print(''.join(map(str, lst)))

3
123


# Basic Data Types

6/ List Comprehensions

Let's learn about list comprehensions! You are given three integers x, y and z representing the dimensions of a cuboid along with an integer n. Print a list of all possible coordinates given by (i, j, k) on a 3D grid where the sum of  is not equal to i + j + k. Here, 0 <= i <= x, 0 <= j <= y, 0 <= k <= z. Please use list comprehensions rather than multiple loops, as a learning exercise.

In [ ]:
# Method 1: for loop
x, y, z, n = (int(input()) for _ in range(4))
print ([[a,b,c] for a in range(0, x+1) for b in range(0, y+1) for c in range(0, z+1) if a + b + c != n ])

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


7/ Find the Runner-Up Score!

Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given  scores. Store them in a list and find the score of the runner-up.

In [ ]:
# Method 1: using set
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    sset = set()
    for i in arr:
        sset.add(i)
    sset.remove(max(sset))
    print(max(sset))

5
2 3 6 6 5
{2, 3, 5, 6}
5


In [ ]:
# Method 2: using list
if __name__ == '__main__':    
    n = int(input())
    arr = list(map(int, input().split()))
    a = max(arr)
    for x in range(len(arr)-1,-1,-1):
            if arr[x] == a:
                    arr.remove(arr[x])
    print(max(arr))

5
2 3 6 6 5
5


8/ Nested Lists

Given the names and grades for each student in a class of  students, store them in a nested list and print the name(s) of any student(s) having the second lowest grade.

Note: If there are multiple students with the second lowest grade, order their names alphabetically and print each name on a new line.

In [ ]:
# Method 1:
marksheet = []
for _ in range(0,int(input())):
    marksheet.append([input(), float(input())])

second_highest = sorted(list(set([marks for name, marks in marksheet])))[1]
print('\n'.join([a for a,b in sorted(marksheet) if b == second_highest]))

5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Berry
Harry


In [ ]:
# Method 2: 
n = int(input())
marksheet = [[input(), float(input())] for _ in range(n)]

second_highest = sorted(list(set([marks for name, marks in marksheet])))[1]
print("Box: ", [marks for name, marks in marksheet])
print("Set: ", set([marks for name, marks in marksheet]))
print("List: ", list(set([marks for name, marks in marksheet])))
print("Sorted list: ", sorted(list(set([marks for name, marks in marksheet]))))
print(second_highest)
print('\n'.join([a for a,b in sorted(marksheet) if b == second_highest]))

5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Box:  [37.21, 37.21, 37.2, 41.0, 39.0]
Set:  {41.0, 37.2, 37.21, 39.0}
List:  [41.0, 37.2, 37.21, 39.0]
Sorted list:  [37.2, 37.21, 39.0, 41.0]
37.21
Berry
Harry


9/ Find the Percentage


The provided code stub will read in a dictionary containing key/value pairs of name:[marks] for a list of students. Print the average of the marks array for the student name provided, showing 2 places after the decimal.

In [ ]:
# Import decimal
from decimal import Decimal
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split() # Single asterisk as used in function declaration allows variable number of arguments passed from calling environment. Inside the function it behaves as a tuple.
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()

# Extract the values into a list: query_scores
query_scores = student_marks[query_name]

# Sum the scores in the list: total_scores
total_scores = sum(query_scores)

# Convert the floats to decimals and average the scores: avg
avg = Decimal(total_scores/3)

# Print the mean of the scores, correct to two decimals
print(round(avg,2))


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


10/ Lists

Consider a list (list = []). You can perform the following commands:

insert i e: Insert integer e at position i.

print: Print the list.

remove e: Delete the first occurrence of integer e.

append e: Insert integer  at the end of the list.

sort: Sort the list.

pop: Pop the last element from the list.

reverse: Reverse the list.

Initialize your list and read in the value of  followed by  lines of commands where each command will be of the  types listed above. Iterate through each command in order and perform the corresponding operation on your list.

In [ ]:
def handler(result):
    inp = input().split()
    command = inp[0]
    values = inp[1:]
    if command == 'print':
        print(result)
    else:
        execute = 'result.' + command + "(" + ",".join(values) + ")"
        eval(execute)


result = []
for i in range(int(input())):
    handler(result)

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


11/ Tuples

Given an integer, n, and n space-separated integers as input, create a tuple, t, of those n integers. Then compute and print the result of hash(t).

Note: hash() is one of the functions in the __builtins__ module, so it need not be imported.

In [ ]:
n = int(input())
print(hash(tuple(map(int, input().split()))))

2
1 2
3713081631934410656


12/ Floor, Ceil and Rint

You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

In [ ]:
# Method 1:
import numpy
numpy.set_printoptions(sign=' ')
a = numpy.array(input().split(),float)
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
# Method 2:
import numpy as np
np.set_printoptions(legacy = '1.13')
ar = np.array(input().strip().split(), float)
print(np.floor(ar), np.ceil(ar), np.rint(ar), sep = "\n")

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# String

13/ sWAP cASE

You are given a string and your task is to swap cases. In other words, convert all lowercase letters to uppercase letters and vice versa.

In [ ]:
def swap_case(s):
    result = ""
    for letter in s:
        if letter == letter.upper():
            result += letter.lower()
        else:
            result += letter.upper()
    return result

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


14/ String Split and Join

In Python, a string can be split on a delimiter.

You are given a string. Split the string on a " " (space) delimiter and join using a - hyphen.

In [ ]:
def split_and_join(line):
    x=line.split(" ") 
    x='-'.join(x)    
    return x

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is a string
this-is-a-string
